# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.3.6
_src_path: https://github.com/jupyterlab/extension-template
author_email: ajshah@ucsd.edu
author_name: Ayush Shah
has_binder: true
has_settings: false
kind: frontend
labextension_name: jupyterlab_apod
project_short_description: ' Show a random NASA Astronomy Picture of the Day in a
    JupyterLab panel'
python_name: jupyterlab_apod
repository: https://github.com/Ayush1124/dstl_test
test: true

